"use client";

import { useState } from "react";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";
import { relativeTime } from "@/lib/utils";
import { formatDateTime } from "@/lib/formatters";
import { Button } from "@/components/ui/button";
import { ChevronDown, ChevronRight, FileText, Package, Box } from "lucide-react";

// ─── Invoice detail row ──────────────────────────────────────────────────────

type InvoiceSummary = {
  _id: string;
  invoiceNumber: string;
  transferId: string;
  fromBranchName: string;
  toBranchName: string;
  totalItems: number;
  status: string;
  createdAt: number;
};

function InvoiceRow({ invoice }: { invoice: InvoiceSummary }) {
  const [expanded, setExpanded] = useState(false);

  const detail = useQuery(
    api.invoices.internalInvoices.getBranchInvoiceDetail,
    expanded ? { invoiceId: invoice._id as Id<"internalInvoices"> } : "skip"
  );

  return (
    <>
      <tr
        className="border-b hover:bg-muted/30 transition-colors cursor-pointer"
        onClick={() => setExpanded(!expanded)}
      >
        <td className="px-4 py-3 font-medium text-sm">{invoice.invoiceNumber}</td>
        <td className="px-4 py-3 text-sm">{invoice.fromBranchName}</td>
        <td className="px-4 py-3 text-sm">{invoice.toBranchName}</td>
        <td className="px-4 py-3 text-sm text-right tabular-nums">{invoice.totalItems} pcs</td>
        <td className="px-4 py-3 text-sm text-muted-foreground whitespace-nowrap">
          {relativeTime(invoice.createdAt)}
        </td>
        <td className="px-4 py-3 w-8">
          {expanded
            ? <ChevronDown className="h-4 w-4 text-muted-foreground" />
            : <ChevronRight className="h-4 w-4 text-muted-foreground" />}
        </td>
      </tr>
      {expanded && (
        <tr className="border-b bg-muted/20">
          <td colSpan={6} className="px-6 py-4">
            {!detail ? (
              <div className="animate-pulse space-y-2">
                {Array.from({ length: 3 }).map((_, i) => (
                  <div key={i} className="h-4 rounded bg-muted w-full" />
                ))}
              </div>
            ) : (
              <div className="space-y-4 max-w-4xl">
                {/* Header info */}
                <div className="flex flex-wrap gap-x-8 gap-y-1 text-xs text-muted-foreground">
                  <span>Invoice: <span className="text-foreground font-medium">{detail.invoice.invoiceNumber}</span></span>
                  <span>Date: <span className="text-foreground font-medium">{formatDateTime(detail.invoice.createdAt)}</span></span>
                  <span>Generated by: <span className="text-foreground font-medium">{detail.generatedByName}</span></span>
                  <span>Mode: <span className="text-foreground font-medium">{detail.deliveryMode === "box" ? "Box" : "Piece"}</span></span>
                </div>

                {/* From/To */}
                <div className="grid grid-cols-2 gap-4 text-xs">
                  <div>
                    <p className="font-semibold text-muted-foreground mb-0.5">From (Warehouse)</p>
                    <p className="font-medium">{detail.fromBranch.name}</p>
                    {detail.fromBranch.address && <p className="text-muted-foreground">{detail.fromBranch.address}</p>}
                  </div>
                  <div>
                    <p className="font-semibold text-muted-foreground mb-0.5">To (Branch)</p>
                    <p className="font-medium">{detail.toBranch.name}</p>
                    {detail.toBranch.address && <p className="text-muted-foreground">{detail.toBranch.address}</p>}
                  </div>
                </div>

                {/* Box breakdown (if box mode) */}
                {detail.deliveryMode === "box" && detail.boxes.length > 0 && (
                  <div className="space-y-3">
                    {detail.boxes.map((box) => (
                      <div key={box.boxCode} className="rounded border overflow-hidden">
                        <div className="flex items-center gap-2 px-3 py-2 bg-muted/50 border-b">
                          <Box className="h-3.5 w-3.5 text-muted-foreground" />
                          <span className="text-xs font-semibold">Box {box.boxNumber}</span>
                          <span className="text-xs text-muted-foreground font-mono">{box.boxCode}</span>
                          <span className="ml-auto text-xs text-muted-foreground">{box.items.reduce((s, i) => s + i.quantity, 0)} pcs</span>
                        </div>
                        <table className="w-full text-xs">
                          <thead>
                            <tr className="border-b">
                              <th className="text-left px-3 py-1.5 font-medium text-muted-foreground">SKU</th>
                              <th className="text-left px-3 py-1.5 font-medium text-muted-foreground">Product</th>
                              <th className="text-left px-3 py-1.5 font-medium text-muted-foreground">Size</th>
                              <th className="text-left px-3 py-1.5 font-medium text-muted-foreground">Color</th>
                              <th className="text-right px-3 py-1.5 font-medium text-muted-foreground">Qty</th>
                            </tr>
                          </thead>
                          <tbody>
                            {box.items.map((item, idx) => (
                              <tr key={idx} className="border-b last:border-0">
                                <td className="px-3 py-1.5 font-mono">{item.sku}</td>
                                <td className="px-3 py-1.5">{item.styleName}</td>
                                <td className="px-3 py-1.5">{item.size}</td>
                                <td className="px-3 py-1.5">{item.color}</td>
                                <td className="px-3 py-1.5 text-right">{item.quantity}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    ))}
                  </div>
                )}

                {/* Flat items table (piece mode) */}
                {(detail.deliveryMode === "piece" || detail.boxes.length === 0) && (
                  <div className="rounded border overflow-hidden">
                    <table className="w-full text-xs">
                      <thead>
                        <tr className="bg-muted/50 border-b">
                          <th className="text-left px-3 py-2 font-medium text-muted-foreground">SKU</th>
                          <th className="text-left px-3 py-2 font-medium text-muted-foreground">Product</th>
                          <th className="text-left px-3 py-2 font-medium text-muted-foreground">Size</th>
                          <th className="text-left px-3 py-2 font-medium text-muted-foreground">Color</th>
                          <th className="text-right px-3 py-2 font-medium text-muted-foreground">Qty</th>
                        </tr>
                      </thead>
                      <tbody>
                        {detail.items.map((item) => (
                          <tr key={item._id} className="border-b last:border-0">
                            <td className="px-3 py-1.5 font-mono">{item.sku}</td>
                            <td className="px-3 py-1.5">{item.styleName}</td>
                            <td className="px-3 py-1.5">{item.size}</td>
                            <td className="px-3 py-1.5">{item.color}</td>
                            <td className="px-3 py-1.5 text-right">{item.quantity}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}

                {/* Total summary */}
                <div className="flex justify-end">
                  <div className="text-xs">
                    <span className="text-muted-foreground">Total: </span>
                    <span className="font-bold">
                      {detail.items.reduce((s, i) => s + i.quantity, 0)} pieces
                    </span>
                    {detail.deliveryMode === "box" && (
                      <span className="ml-3 text-muted-foreground">
                        in {detail.boxes.length} {detail.boxes.length === 1 ? "box" : "boxes"}
                      </span>
                    )}
                  </div>
                </div>
              </div>
            )}
          </td>
        </tr>
      )}
    </>
  );
}

// ─── Page ────────────────────────────────────────────────────────────────────

export default function BranchInvoicesPage() {
  const [cursor, setCursor] = useState<number | undefined>(undefined);

  const result = useQuery(api.invoices.internalInvoices.listBranchInvoices, {
    limit: 10,
    cursor,
  });

  const invoices = result?.invoices ?? [];
  const hasMore = result?.hasMore ?? false;

  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-center gap-2">
          <Package className="h-6 w-6 text-primary" />
          <h1 className="text-2xl font-bold">Transfer Receipts</h1>
        </div>
        <p className="text-sm text-muted-foreground mt-1">
          Packing slips generated from stock transfers.
        </p>
      </div>

      {/* Table */}
      <div className="rounded-lg border bg-card">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b bg-muted/50">
                <th className="text-left px-4 py-3 font-medium text-muted-foreground">Invoice #</th>
                <th className="text-left px-4 py-3 font-medium text-muted-foreground">From</th>
                <th className="text-left px-4 py-3 font-medium text-muted-foreground">To</th>
                <th className="text-right px-4 py-3 font-medium text-muted-foreground">Items</th>
                <th className="text-left px-4 py-3 font-medium text-muted-foreground">Date</th>
                <th className="w-8 px-4 py-3"></th>
              </tr>
            </thead>
            <tbody>
              {result === undefined &&
                Array.from({ length: 5 }).map((_, i) => (
                  <tr key={i} className="border-b animate-pulse">
                    {Array.from({ length: 6 }).map((_, j) => (
                      <td key={j} className="px-4 py-3">
                        <div className="h-4 rounded bg-muted w-full" />
                      </td>
                    ))}
                  </tr>
                ))}

              {result !== undefined && invoices.length === 0 && (
                <tr>
                  <td colSpan={6} className="px-4 py-12 text-center">
                    <FileText className="h-8 w-8 text-muted-foreground mx-auto mb-2" />
                    <p className="text-muted-foreground">No transfer receipts found.</p>
                    <p className="text-xs text-muted-foreground mt-1">
                      Receipts are generated automatically when transfers are delivered.
                    </p>
                  </td>
                </tr>
              )}

              {invoices.map((inv) => (
                <InvoiceRow key={inv._id} invoice={inv} />
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Pagination */}
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          {invoices.length > 0 ? `Showing ${invoices.length} receipts` : ""}
        </p>
        <div className="flex gap-2">
          {cursor !== undefined && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => setCursor(undefined)}
            >
              Back to latest
            </Button>
          )}
          {hasMore && result?.nextCursor && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => setCursor(result.nextCursor)}
            >
              Load older
            </Button>
          )}
        </div>
      </div>
    </div>
  );
}
